### ISSUE TITLE
`npm install --save-dev nodemon` is giving `404 Not Found: @remy/pstree@^1.1.0`

### ISSUE THREAD

**Issue by mannypamintuan** [remy/pstree#1]
I tried install nodemon in a project and received a 404 with respect to pstree, this may be affecting other apps that rely on `@remy/pstree` as a dependency.

I saw on NPM that this lib was updated about 21ish hours ago and wanted to bring this to your attention.
:)

```
$ npm install --save-dev nodemon
npm ERR! code E404
npm ERR! 404 Not Found: @remy/pstree@^1.1.0
```
```
OSX
npm --version 5.6.0
node --version v8.9.3
```

**Comment by donalhenry** [comment]
I was getting this issue with version 1.0.1, and resolved it by updating the version of artifactory that we were using.  The older version had trouble with the "@".  

Now getting "404 User not found : @remy/pstree" but only on macOS.  Works fine on linux.  Puzzling.

**Comment by remy** [comment]
Problem is that I can see it right here: http://registry.npmjs.org/@remy%2Fpstree

**Comment by bjartenilsen** [comment]
I am getting same issue - but only when using https to connect to  registry.npmjs.org

**Comment by bjartenilsen** [comment]
My solution:  

When Using Nexus as proxy, and the requests are sent from npm win url encoded slash. 

For some reason, when using @ in package name, the latter / is encoded to %2f  - this is not default legal in our apache in front. 

Adding

    AllowEncodedSlashes On

to apache config resolved this issue for us

**Comment by borispap** [comment]
See related issue was resolved in 
https://issues.sonatype.org/browse/NEXUS-11630
